ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_isp/isp_hw_mgr/include
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_smmu/
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sync
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_utils

obj-$(CONFIG_LEGACY_CAMERA) += isp_hw_mgr/
obj-$(CONFIG_LEGACY_CAMERA) += cam_isp_dev.o cam_isp_context.o
