ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_jpeg
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_jpeg/jpeg_hw/include
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_jpeg/jpeg_hw/
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_jpeg/jpeg_hw/jpeg_hw_mgr/include
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_jpeg/jpeg_hw/jpeg_dma_hw

obj-$(CONFIG_LEGACY_CAMERA) += jpeg_dma_dev.o jpeg_dma_core.o jpeg_dma_soc.o
