ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sync
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_smmu
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_cdm
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_fd
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_fd/fd_hw_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_fd/fd_hw_mgr/fd_hw
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_cpas/include

obj-$(CONFIG_LEGACY_CAMERA) += cam_fd_hw_dev.o cam_fd_hw_core.o cam_fd_hw_soc.o
