ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_smmu/

obj-$(CONFIG_LEGACY_CAMERA) += cam_cci_dev.o cam_cci_core.o cam_cci_soc.o
