ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_smmu/
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sync
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_core

obj-$(CONFIG_LEGACY_CAMERA) += cam_context.o cam_context_utils.o cam_node.o cam_subdev.o
