ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sync
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_smmu
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_cdm
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_lrme
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_lrme/lrme_hw_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers0
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_cpas/include

obj-$(CONFIG_LEGACY_CAMERA) += cam_lrme_hw_dev.o cam_lrme_hw_core.o cam_lrme_hw_soc.o
