ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_sync
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_smmu
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_jpeg/jpeg_hw/
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_jpeg/jpeg_hw/include
ccflags-y += -I$(srctree)/techpack/camera-legacy/drivers/cam_cpas/include/

obj-$(CONFIG_LEGACY_CAMERA) += jpeg_hw/
obj-$(CONFIG_LEGACY_CAMERA) += cam_jpeg_dev.o cam_jpeg_context.o
